### ISSUE TITLE
Should `showStoreName` show store's name outside?

### ISSUE THREAD

**Issue by blackcater** [cwdx/pinia-logger#1]
I find this project from npm. Thanks for your hard-working.

When I use pinia's `defineStore`, different stores maybe have the same action name. So show store's name outside is more convenient and intuitionistic.

So the default value of `showStoreName` should be `true`.

![image](https://user-images.githubusercontent.com/9465551/149066124-9f1f6ced-8846-4300-a1d8-e51801eff3d8.png)

**Comment by blackcater** [comment]
PR #2

**Comment by cwdx** [comment]
Implemented in `1.3.0` thanks @blackcater 
https://www.npmjs.com/package/pinia-logger/v/1.3.0
